<?php
return [
	'timeout'  => '2500',
	'error_null' => "Please enter Book ID!",
	'error_exist'=> "Book item has exist!",
	'error_notexist'=> "Book item does not exist!",
	'number_pages' => 9,
	'number_image_default' => 1,
	'number_images_slide' => 3,
	'give_back' => 1,
	'quantity_decrement' => -1,
	'year_begin' => '1990',
	'year_end' => '2020',
	'number_pages' => 9,
	'number_image_default' => 1,
	'number_images_slide' => 3,
	'mail' => 'vddongbk@gmail.com',
	'limit_day' => 30,
	'not_give_back' => '0',
	'max_borrow' => 5,
	'str_max_book_name' => 20,
	'year' => 2016,
	'month' => 8,
	'begin_cut_year' => 0,
	'cut_year' => 4,
	'begin_cut_month' => 5,
	'cut_month' => 2,
	'success' => 200,
];